[package]
name = "cargo-release-pr-test-two"
version = "2.2.2"
edition = "2021"
description = "Second"
license = "MIT"
repository = "https://github.com/mmagician/cargo-release-pr-test"

[dependencies]
cargo-release-pr-test-one = { version = "2.2.0", path = "../one" }
